### ISSUE TITLE
Problem importing after install

### ISSUE THREAD

**Issue by tom-montgomery** [AlexArcPy/registrant#2]
Hi Alex, I am using python 2.7.8 and ArcGIS 10.3.1

- Downloaded zip and unpacked into desktop folder.
- Installed in powershell using the method in your Installation guide:
- Tried reinstall after first try to no avail. used pip uninstall registrant

`python setup.py install`

powershell output:

>  PS C:\users\user\desktop\registrant-master> python setup.py install
> running install
> running bdist_egg
> running egg_info
> writing requirements to registrant.egg-info\requires.txt
> writing registrant.egg-info\PKG-INFO
> writing top-level names to registrant.egg-info\top_level.txt
> writing dependency_links to registrant.egg-info\dependency_links.txt
> reading manifest file 'registrant.egg-info\SOURCES.txt'
> writing manifest file 'registrant.egg-info\SOURCES.txt'
> installing library code to build\bdist.win32\egg
> running install_lib
> running build_py
> creating build\bdist.win32\egg
> creating build\bdist.win32\egg\registrant
> creating build\bdist.win32\egg\registrant\app
> creating build\bdist.win32\egg\registrant\app\css
> copying build\lib\registrant\app\css\bootstrap.min.css -> build\bdist.win32\egg\registrant\app\css
> copying build\lib\registrant\app\css\buttons.dataTables.min.css -> build\bdist.win32\egg\registrant\app\css
> copying build\lib\registrant\app\css\dashboard.css -> build\bdist.win32\egg\registrant\app\css
> copying build\lib\registrant\app\css\dataTables.bootstrap.min.css -> build\bdist.win32\egg\registrant\app\css
> copying build\lib\registrant\app\css\ie10-viewport-bug-workaround.css -> build\bdist.win32\egg\registrant\app\css
> creating build\bdist.win32\egg\registrant\app\fonts
> copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.eot -> build\bdist.win32\egg\registrant\app\fonts
> copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.svg -> build\bdist.win32\egg\registrant\app\fonts
> copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.ttf -> build\bdist.win32\egg\registrant\app\fonts
> copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.woff -> build\bdist.win32\egg\registrant\app\fonts
> copying build\lib\registrant\app\fonts\glyphicons-halflings-regular.woff2 -> build\bdist.win32\egg\registrant\app\fonts
> creating build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\js\bootstrap.min.js -> build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\js\buttons.print.min.js -> build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\js\dataTables.bootstrap.min.js -> build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\js\dataTables.buttons.min.js -> build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\js\holder.min.js -> build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\js\ie-emulation-modes-warning.js -> build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\js\ie10-viewport-bug-workaround.js -> build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\js\jquery.dataTables.min.js -> build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\js\jquery.min.js -> build\bdist.win32\egg\registrant\app\js
> copying build\lib\registrant\app\__init__.py -> build\bdist.win32\egg\registrant\app
> creating build\bdist.win32\egg\registrant\html-template
> copying build\lib\registrant\html-template\template.html -> build\bdist.win32\egg\registrant\html-template
> copying build\lib\registrant\html-template\__init__.py -> build\bdist.win32\egg\registrant\html-template
> copying build\lib\registrant\_build_html.py -> build\bdist.win32\egg\registrant
> copying build\lib\registrant\_config.py -> build\bdist.win32\egg\registrant
> copying build\lib\registrant\_data_objects.py -> build\bdist.win32\egg\registrant
> copying build\lib\registrant\_geodatabase.py -> build\bdist.win32\egg\registrant
> copying build\lib\registrant\_reporter.py -> build\bdist.win32\egg\registrant
> copying build\lib\registrant\_util_mappings.py -> build\bdist.win32\egg\registrant
> copying build\lib\registrant\__init__.py -> build\bdist.win32\egg\registrant
> byte-compiling build\bdist.win32\egg\registrant\app\__init__.py to __init__.pyc
> byte-compiling build\bdist.win32\egg\registrant\html-template\__init__.py to __init__.pyc
> byte-compiling build\bdist.win32\egg\registrant\_build_html.py to _build_html.pyc
> byte-compiling build\bdist.win32\egg\registrant\_config.py to _config.pyc
> byte-compiling build\bdist.win32\egg\registrant\_data_objects.py to _data_objects.pyc
> byte-compiling build\bdist.win32\egg\registrant\_geodatabase.py to _geodatabase.pyc
> byte-compiling build\bdist.win32\egg\registrant\_reporter.py to _reporter.pyc
> byte-compiling build\bdist.win32\egg\registrant\_util_mappings.py to _util_mappings.pyc
> byte-compiling build\bdist.win32\egg\registrant\__init__.py to __init__.pyc
> creating build\bdist.win32\egg\EGG-INFO
> copying registrant.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
> copying registrant.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
> copying registrant.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
> copying registrant.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
> copying registrant.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
> zip_safe flag not set; analyzing archive contents...
> registrant._config: module references __file__
> creating 'dist\registrant-0.1-py2.7.egg' and adding 'build\bdist.win32\egg' to it
> removing 'build\bdist.win32\egg' (and everything under it)
> Processing registrant-0.1-py2.7.egg
> creating c:\python27\arcgis10.3\lib\site-packages\registrant-0.1-py2.7.egg
> Extracting registrant-0.1-py2.7.egg to c:\python27\arcgis10.3\lib\site-packages
> Adding registrant 0.1 to easy-install.pth file
> 
> Installed c:\python27\arcgis10.3\lib\site-packages\registrant-0.1-py2.7.egg
> Processing dependencies for registrant==0.1
> Searching for beautifulsoup4==4.6.0
> Best match: beautifulsoup4 4.6.0
> Adding beautifulsoup4 4.6.0 to easy-install.pth file
> 
> Using c:\python27\arcgis10.3\lib\site-packages
> Searching for pandas==0.20.3
> Best match: pandas 0.20.3
> Processing pandas-0.20.3-py2.7-win32.egg
> pandas 0.20.3 is already the active version in easy-install.pth
> 
> Using c:\python27\arcgis10.3\lib\site-packages\pandas-0.20.3-py2.7-win32.egg
> Searching for numpy==1.7.1
> Best match: numpy 1.7.1
> Adding numpy 1.7.1 to easy-install.pth file
> 
> Using c:\python27\arcgis10.3\lib\site-packages
> Searching for pytz==2016.10
> Best match: pytz 2016.10
> Adding pytz 2016.10 to easy-install.pth file
> 
> Using c:\python27\arcgis10.3\lib\site-packages
> Searching for python-dateutil==2.6.0
> Best match: python-dateutil 2.6.0
> Adding python-dateutil 2.6.0 to easy-install.pth file
> 
> Using c:\python27\arcgis10.3\lib\site-packages
> Searching for six==1.10.0
> Best match: six 1.10.0
> Adding six 1.10.0 to easy-install.pth file
> 
> Using c:\python27\arcgis10.3\lib\site-packages
> Finished processing dependencies for registrant==0.1
> PS C:\users\user\desktop\registrant-master>
> 

and my results when attempting to import in python 2.7.8 shell:

```
  import registrant
 
 Traceback (most recent call last):
   File "<pyshell#0>", line 1, in <module>
     import registrant
   File "C:\Python27\ArcGIS10.3\lib\site-packages\registrant-0.1-py2.7.egg\registrant\__init__.py", line 2, in <module>
    from ._reporter import domains2html, fcs2html, tables2html, gdb2html, report_gdb_as_html
   File "C:\Python27\ArcGIS10.3\lib\site-packages\registrant-0.1-py2.7.egg\registrant\_reporter.py", line 19, in <module>
     pd.set_option('display.width', 250)
   File "C:\Python27\ArcGIS10.3\lib\site-packages\pandas\core\config.py", line 193, in __call__
     return self.__func__(*args, **kwds)
   File "C:\Python27\ArcGIS10.3\lib\site-packages\pandas\core\config.py", line 98, in _set_option
     key = _get_single_key(pat, silent)
   File "C:\Python27\ArcGIS10.3\lib\site-packages\pandas\core\config.py", line 76, in _get_single_key
     raise KeyError('No such keys(s)')
 KeyError: 'No such keys(s)'
  from registrant import *
 
 Traceback (most recent call last):
   File "<pyshell#1>", line 1, in <module>
     from registrant import *
   File "C:\Python27\ArcGIS10.3\lib\site-packages\registrant-0.1-py2.7.egg\registrant\__init__.py", line 2, in <module>
     from ._reporter import domains2html, fcs2html, tables2html, gdb2html, report_gdb_as_html
   File "C:\Python27\ArcGIS10.3\lib\site-packages\registrant-0.1-py2.7.egg\registrant\_reporter.py", line 11, in <module>
     from . import _geodatabase as GDB
 ImportError: cannot import name _geodatabase
```

**Comment by AlexArcPy** [comment]
Thanks for posting. This looks interesting. I have set a fresh VM with Windows 7 and ArcGIS 10.3.1, so the environment matches yours.
1. Downloaded and installed `pip` from https://bootstrap.pypa.io/get-pip.py. This installed `setuptools`.
2. Added `C:\Python27\ArcGIS10.3` to the Windows `PATH` variable.
3. Installed `Microsoft Visual C++ Compiler for Python 2.7` available from `http://aka.ms/vcpython27` (required to install compiled `pandas`). ArcGIS 10.3.1 ships with an older version of `pandas`.
3. Downloaded the repo and used Windows CMD while being in the folder with unpacked repo to run `python setup.py install`.
4. Open IDLE and run `import registrant`. No problem.

Let's try troubleshooting your installation. 

`import pandas as pd` and `pd.__version__` should give you `0.20.3`. Maybe you have screwed something with paths to two different pandas and now you cannot import the right one?

As the worst case scenario, would re-installing ArcGIS to get a fresh Python be an applicable solution?

**Comment by tom-montgomery** [comment]
Just checked my pandas version and I think you are onto something there as it shows '0.10.1'. I will try to upgrade it, but if i remember correctly ArcGIS 10.3x depency on numpy 1.7.1 prevents me from upgrading to 0.20.3 if i want to continue in this environment. I will let you know if I am able.

**Comment by AlexArcPy** [comment]
`numpy.__version__` gives me `1.7.1`. Have no problem operating ArcGIS 10.3.1 on this machine.

**Comment by tom-montgomery** [comment]
tried to upgrade pandas and it broke my arcpy/numpy for my arcgis interpreter.. reinstalling now will let you know the status afterwards.

**Comment by tom-montgomery** [comment]
got it to work after reinstalling ArcGIS. Not sure what was going on with my python environment/interpreter. Thanks!

**Comment by AlexArcPy** [comment]
Glad you got it working! Perhaps the initial attempt to upgrade `pandas` update broke something and the only way to fix it was to reinstall the whole Python environment. Feel free to submit any requests on the functionality you would think would be helpful!
