### ISSUE TITLE
relationship class location causes reporter error

### ISSUE THREAD

**Issue by dev-pra** [AlexArcPy/registrant#8]
There is a dataset with a feature class. A table is outside the dataset. If a relationship class is created between the feature class and the table, and the relationship class is placed outside the dataset the reporter.gdb2html function gives an error.

![image](https://user-images.githubusercontent.com/7099459/80865064-78049680-8c8f-11ea-8901-128e49b8733c.png)

The workaround is to move such relationship classes to the dataset.
The code must work irrespective of the location of the relationship class as ArcGIS does not enforce any such rule. Attached FGDB for recreating the issue
[Issue_gdb1.gdb.zip](https://github.com/AlexArcPy/registrant/files/4567753/Issue_gdb1.gdb.zip)

**Comment by AlexArcPy** [comment]
Hi @dev-pra ! Thanks for sharing this and providing the data to reproduce. I am very sorry the tool doesn't provide a more robust behavior for your use case. Sadly I don't have access to ArcGIS license any longer so it will be rather difficult to make changes as I won't be able to run any tests.

Please feel free to modify the source code to submit a PR with the changes. If that's not an option, I am afraid you'll need to move your relationship class to make it work or set `do_report_relclasses=False` in the call to `gdb2html()` - this will ignore the relclasses and the HTML report should be created.
